[package]
edition = "2021"
name = "rocket-study"
version = "0.1.0"

[dependencies]
rocket = {version = "0.5.1", features = ["json", "http2", "uuid"]}

[dependencies.uuid]
features = ["v1", "v4"]
version = "1"
